

name: Prueba y despliegue

on:
  push:
    branches:
      - main

jobs:
  prueba-y-despliegue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar dependencias de desarrollo
        run: npm install --only=dev

      - name: Ejecutar pruebas
        run: npm test

      - name: Login a Docker
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Crear imagen de Docker
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: kronn0514/lab3-github-actions
          

      - name: Subir imagen a DockerHub
        run: docker push kronn0514/lab3-github-actions